name       : libspatialindex
version    : 1.8.5
release    : 1
source     :
    - https://github.com/libspatialindex/libspatialindex/archive/1.8.5.tar.gz : 93cce77269612f45287b521d5afdfb245be2b93b8b6438d92f8b9e0bdb37059d
license    : MIT
component  : programming
summary    : C++ implementation of R*-tree, an MVR-tree and a TPR-tree with C API
description: |
    C++ implementation of R*-tree, an MVR-tree and a TPR-tree with C API
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
