name       : libspatialindex
version    : 1.9.3
release    : 3
source     :
    - https://github.com/libspatialindex/libspatialindex/releases/download/1.9.3/spatialindex-src-1.9.3.tar.bz2 : 4a529431cfa80443ab4dcd45a4b25aebbabe1c0ce2fa1665039c80e999dcc50a
license    : MIT
component  : programming.library
homepage   : https://libspatialindex.org
summary    : C++ implementation of R*-tree, an MVR-tree and a TPR-tree with C API
description: |
    C++ implementation of R*-tree, an MVR-tree and a TPR-tree with C API.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
